services:
  traefik:
    image: traefik
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    command:
      - --api.dashboard=true
      - --providers.docker=true
      - --providers.docker.exposedbydefault=false
      - --entrypoints.web.address=:80
      - --entrypoints.websecure.address=:443
      - --entrypoints.websecure.http.tls=true
      - --entrypoints.web.http.redirections.entrypoint.to=websecure
      - --entrypoints.web.http.redirections.entrypoint.scheme=https
      - --entrypoints.web.http.redirections.entrypoint.permanent=true
      - --log=true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(`traefik.worldbuild.localhost`)"
      - "traefik.http.routers.traefik.service=api@internal"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  studio:
    image: node:alpine
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
      - ./api:/app/api
    working_dir: /app/api
    env_file:
      - ./api/.env
    command: npx prisma studio -n 0.0.0.0
    expose:
      - 5555
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.studio.rule=Host(`studio.worldbuild.localhost`)"

  api:
    image: worldbuild-node
    build:
      context: .docker
      dockerfile: Dockerfile
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
      - ./api:/app/api
    working_dir: /app/api
    command: npm run start:dev
    environment:
      - PUID=1000
      - PGID=1000
    env_file:
      - ./api/.env
    expose:
      - 3000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`api.worldbuild.localhost`)"

  app:
    image: worldbuild-node
    build:
      context: .docker
      dockerfile: Dockerfile
    volumes:
      - ./package.json:/app/package.json
      - ./package-lock.json:/app/package-lock.json
      - ./node_modules:/app/node_modules
      - ./app:/app/app
    working_dir: /app/app
    command: npm run dev
    environment:
      - PUID=1000
      - PGID=1000
    expose:
      - 5173
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`worldbuild.localhost`)"
  
  database:
    image: postgres:alpine
    environment:
      POSTGRES_PASSWORD: worldbuild
      POSTGRES_USER: worldbuild
      POSTGRES_DB: app
    volumes:
      - database:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  database:
